# Generated by Django 4.2.1 on 2023-06-03 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='like',
        ),
        migrations.AddField(
            model_name='like',
            name='sl',
            field=models.IntegerField(default=0),
        ),
    ]
